## first numpy code

In [ ]:
print("Hello, World!")

Hello, World!


In [2]:

import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


### 2D array

In [9]:
arr2 = np.array([[1,2],[3,4]])
print(arr2)
print(arr2.shape) #check the shape of the array
print(arr2[1,1])  #access the element at row 0 and column

[[1 2]
 [3 4]]
(2, 2)
4


## Zeros, Ones, Random

In [25]:
print(np.zeros((2,3)))
print(np.ones((2,2)))
print(np.random.rand(2,2))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.03433488 0.37391562]
 [0.18217532 0.22715156]]


In [26]:
# 1️⃣ Create array
arr = np.arange(1, 11)
print("Original:", arr)

# 2️⃣ Even numbers
even = arr[arr % 2 == 0]
print("Even:", even)

Original: [ 1  2  3  4  5  6  7  8  9 10]
Even: [ 2  4  6  8 10]


## indexing & slicing

In [24]:
arr = np.array([10,20,30,40])

print(arr[0])      # 10
print(arr[1:3])    # [20 30]

10
[20 30]


In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)   # [5 7 9]
print(a * 2)   # [2 4 6]

[5 7 9]
[2 4 6]


## maths functions

In [18]:
arr = np.array([1,2,3,4])

print(np.mean(arr)) # mean of the array
print(np.sum(arr)) # sum of the array
print(np.max(arr)) # maximum value in the array

2.5
10
4


## matrix multiplication
## dot = multipy + sum

In [19]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


## reshape the array 

In [27]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


Mini Exercise 2 – 2D Array (Matrix)
🎯 Task:

1️⃣ Create 3x3 matrix with numbers 1–9
2️⃣ Find row sum
3️⃣ Find column sum
4️⃣ Transpose matrix

In [29]:
arr = np.arange(1, 10).reshape(3,3)

print("Matrix:\n", arr)

# Row sum
print("Row sum:", arr.sum(axis=1))

# Column sum
print("Column sum:", arr.sum(axis=0))

# Transpose
print("Transpose:\n", arr.T)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row sum: [ 6 15 24]
Column sum: [12 15 18]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


🎯 Task:

1️⃣ Find students who scored above 60
2️⃣ Normalize marks (divide by 100)
3️⃣ Replace marks below 35 with 0

In [ ]:
marks = np.array([40, 55, 78, 90, 32, 67, 30, 85])

# Above 60
print("Above 60:", marks[marks > 60])

# Normalize
print("Normalized:", marks / 100)

# Replace below 35
marks[marks < 35] = 0
print("Updated Marks:", marks)

Above 60: [78 90 67 85]
Normalized: [0.4  0.55 0.78 0.9  0.32 0.67 0.3  0.85]
Updated Marks: [40 55 78 90  0 67  0 85]


## broadcastng in python`

In [3]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]]


🔥 What is axis in NumPy?

Axis tells NumPy:

👉 Which direction to perform operation.

🧠 Example Matrix
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])

Shape:

(2 rows, 3 columns)
🔹 axis = 0 → Down the rows (column-wise operation)
print(arr.sum(axis=0))

Output:

[5 7 9]

Because:

Column 1: 1 + 4 = 5
Column 2: 2 + 5 = 7
Column 3: 3 + 6 = 9
🔹 axis = 1 → Across columns (row-wise operation)
print(arr.sum(axis=1))

Output:

[ 6 15]

Because:

Row 1: 1 + 2 + 3 = 6
Row 2: 4 + 5 + 6 = 15
🎯 Memory Trick

axis=0 → vertical ↓
axis=1 → horizontal →

🔥 Why axis is Important in ML?

Used in:

Mean normalization

Softmax

Batch operations

Feature scaling

Example:

np.mean(X, axis=0)  # feature-wise mean
np.mean(X, axis=1)  # sample-wise mean

Very common in ML pipelines.