## first numpy code

In [1]:
print("Hello, World!")

Hello, World!


In [2]:

import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


### 2D array

In [9]:
arr2 = np.array([[1,2],[3,4]])
print(arr2)
print(arr2.shape) #check the shape of the array
print(arr2[1,1])  #access the element at row 0 and column

[[1 2]
 [3 4]]
(2, 2)
4


In [10]:
print(np.zeros((2,3)))
print(np.ones((2,2)))
print(np.random.rand(2,2))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.48844635 0.54398486]
 [0.66995507 0.66005409]]
