## first numpy code

In [1]:
print("Hello, World!")

Hello, World!


In [2]:

import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


### 2D array

In [9]:
arr2 = np.array([[1,2],[3,4]])
print(arr2)
print(arr2.shape) #check the shape of the array
print(arr2[1,1])  #access the element at row 0 and column

[[1 2]
 [3 4]]
(2, 2)
4


## Zeros, Ones, Random

In [11]:
print(np.zeros((2,3)))
print(np.ones((2,2)))
print(np.random.rand(2,2))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.08520074 0.91375503]
 [0.90916372 0.68314659]]


In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)   # [5 7 9]
print(a * 2)   # [2 4 6]

[5 7 9]
[2 4 6]


## maths functions

In [18]:
arr = np.array([1,2,3,4])

print(np.mean(arr)) # mean of the array
print(np.sum(arr)) # sum of the array
print(np.max(arr)) # maximum value in the array

2.5
10
4


## matrix multiplication

In [19]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


## reshape the array 

In [20]:
arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]
